.\" SPDX-License-Identifier: LGPL-3.0-or-later
.\" Copyright (C) 2023 Emily "TTG" Banerjee <prs.ttg+afeirsa@pm.me>

.TH af_killhandle 3 "" "" "Afeirsa"
.SH NAME
\fBaf_killhandle\fP \- destroy GL handle

.SH SYNOPSIS
enum af_err \fBaf_killhandle\fP(
struct af_ctx* \fIctx\fP,
struct af_handleset* \fIset\fP,
af_uint_t \fIhandle\fP
)

.SH DESCRIPTION
\fBaf_killhandle\fP destroys a GL handle in the handle set pointed to by
\fIset\fP. The handle to destroy is specified by \fIhandle\fP which was
previously created by a call to \fBaf_mkhandle\fP(3).

\fBaf_killhandle\fP is largely a library-internal call used for destroying
GL objects from other functions.

.SH SEE ALSO
\fBaf_mkhandle\fP(3)

.SH AUTHOR
Emily "TTG" Banerjee (prs.ttg+afeirsa@pm.me)
