.\" SPDX-License-Identifier: LGPL-3.0-or-later
.\" Copyright (C) 2023 Emily "TTG" Banerjee <prs.ttg+afeirsa@pm.me>

.TH af_killvert 3 "" "" "Afeirsa"
.SH NAME
\fBaf_killvert\fP \- destroy vertex layout

.SH SYNOPSIS
enum af_err \fBaf_killvert\fP(
struct af_ctx* \fIctx\fP,
struct af_vert* \fIvert\fP
)

.SH DESCRIPTION
\fBaf_killvert\fP destroys the vertex layout description in the storage pointed
to by \fIbuf\fP which was previously passed to \fBaf_mkvert\fP(3).

.SH SEE ALSO
\fBaf_mkvert\fP(3)

.SH AUTHOR
Emily "TTG" Banerjee (prs.ttg+afeirsa@pm.me)
