.\" SPDX-License-Identifier: LGPL-3.0-or-later
.\" Copyright (C) 2023 Emily "TTG" Banerjee <prs.ttg+afeirsa@pm.me>

.TH af_killbuf 3 "" "" "Afeirsa"
.SH NAME
\fBaf_killbuf\fP \- destroy graphics buffer

.SH SYNOPSIS
enum af_err \fBaf_killbuf\fP(
struct af_ctx* \fIctx\fP,
struct af_buf* \fIbuf\fP
)

.SH DESCRIPTION
\fBaf_killbuf\fP destroys the graphics buffer object in the storage pointed to
by \fIbuf\fP which was previously passed to \fBaf_mkbuf\fP(3).

Reinitializing a new graphics buffer in the same storage is not guaranteed to
resolve any dangling references to a destroyed buffer.

.SH SEE ALSO
\fBaf_mkbuf\fP(3)

.SH AUTHOR
Emily "TTG" Banerjee (prs.ttg+afeirsa@pm.me)
